version: "3.9"
services:
  coordinator_db:
    container_name: coordinator_db
    image: postgres
    restart: always
    volumes:
      - ./coordinator/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: 'revault'
      POSTGRES_PASSWORD: 'revault'
      POSTGRES_DB: 'coordinator_db'

  coordinatord:
    image: coordinatord
    container_name: coordinator
    entrypoint: ["./entrypoint.sh"]
    expose:
      - 8383
    ports:
      - 8383:8383
    volumes:
      - type: bind
        source: ./coordinator
        target: /home/.revault_coordinatord
    container_name: coordinatord
    depends_on:
      - coordinator_db
    build:
      context: ./docker/coordinatord
      dockerfile: Dockerfile
